name: Build
on:
  workflow_dispatch:
  repository_dispatch:
    types: womginx.sh
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -
        name: Private Actions Checkout
        uses: actions/checkout@v2.4.0
      -
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      -
        name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: womginx/
          platforms: linux/amd64
          file: womginx/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ng:test
        continue-on-error: true
