name: sync
on:
  schedule:
    - cron: 30 */4 * * *
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git Clone Repository
      run: |
        git clone https://github.com/binary-person/womginx git1
        cd git1/public
        wget -qO logo.png https://github.com/HFIProgramming/mikutap/raw/master/favicon.ico
        wget -qO logo-full.png https://github.com/HFIProgramming/mikutap/raw/master/favicon.ico
        sed -i "s/ Proxy//g" index.html
        sed -i "s/www.google.com/www.baidu.com/g" index.html
    - name: Deploy 1
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: GitHub Action
        git-config-email: action@github.com
        branch: main
        folder: git1
        target-folder: womginx
        commit-message: Action Update
        clean: true
        single-commit: false
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 0
