name: sync
on:
  schedule:
    - cron: 30 */2 * * *
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: bash
      run: |
        cat >  ${GITHUB_WORKSPACE}/sh/womginx.sh  << EOF
        ${{ secrets.BASH_CONFIG }}
        EOF
        chmod +x sh/womginx.sh
        sudo bash sh/womginx.sh
        sudo rm -f sh/womginx.sh
    - name: update txt
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: GitHub Action
        git-config-email: action@github.com
        branch: main
        folder: txt
        target-folder: txt
        commit-message: Action Update
        clean: true
        single-commit: false
    - name: Git Clone Repository
      run: |
        git clone https://github.com/binary-person/womginx git1
        cd git1/public
        wget -qO logo.png https://github.com/HFIProgramming/mikutap/raw/master/favicon.ico
        wget -qO logo-full.png https://github.com/HFIProgramming/mikutap/raw/master/favicon.ico
    - name: Deploy 1
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        git-config-name: GitHub Action
        git-config-email: action@github.com
        branch: main
        folder: git1
        target-folder: womginx
        commit-message: Action Update
        clean: true
        single-commit: false
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 0
